/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddBDDepartmentInput
 */
export interface AddBDDepartmentInput {
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    depId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    workshopId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    depNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    depName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    depDesc?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddBDDepartmentInput
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    remarks?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDDepartmentInput
     */
    orgID?: string | null;
}
