/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddBDMachineThirdInput
 */
export interface AddBDMachineThirdInput {
    /**
     * 
     * @type {string}
     * @memberof AddBDMachineThirdInput
     */
    groupNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDMachineThirdInput
     */
    groupDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDMachineThirdInput
     */
    resNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDMachineThirdInput
     */
    orgId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddBDMachineThirdInput
     */
    machineType?: number;
    /**
     * 
     * @type {number}
     * @memberof AddBDMachineThirdInput
     */
    maetype?: number;
}
