/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddBDPartInput
 */
export interface AddBDPartInput {
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    partID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    orgID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    partNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    partName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    partDesc?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    partType?: number;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    productType?: number;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    unitId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    attachName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    urlPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    attachment?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    defaultMBDecision?: number;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    mfgGroup?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    fullLeadTime?: number;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    plannerCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    drawingNo?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    supplyType?: number;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    lotSize?: number;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    setupTimeST?: number;
    /**
     * 
     * @type {number}
     * @memberof AddBDPartInput
     */
    resPriority?: number;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    groupNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    familyNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddBDPartInput
     */
    categoryNo?: string | null;
}
