/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDBOMInput
 */
export interface BDBOMInput {
    /**
     * 当前页码
     * @type {number}
     * @memberof BDBOMInput
     */
    page?: number;
    /**
     * 页码容量
     * @type {number}
     * @memberof BDBOMInput
     */
    pageSize?: number;
    /**
     * 排序字段
     * @type {string}
     * @memberof BDBOMInput
     */
    field?: string | null;
    /**
     * 排序方向
     * @type {string}
     * @memberof BDBOMInput
     */
    order?: string | null;
    /**
     * 降序排序
     * @type {string}
     * @memberof BDBOMInput
     */
    descStr?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDBOMInput
     */
    masterPartId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDBOMInput
     */
    subPartId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDBOMInput
     */
    rootPartId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDBOMInput
     */
    needQty?: number;
    /**
     * 
     * @type {number}
     * @memberof BDBOMInput
     */
    level?: number;
}
