/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 假期日历表
 * @export
 * @interface BDCalHoliday
 */
export interface BDCalHoliday {
    /**
     * 雪花Id
     * @type {number}
     * @memberof BDCalHoliday
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof BDCalHoliday
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof BDCalHoliday
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof BDCalHoliday
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof BDCalHoliday
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof BDCalHoliday
     */
    isDelete?: boolean;
    /**
     * HolidayId
     * @type {string}
     * @memberof BDCalHoliday
     */
    holidayId?: string | null;
    /**
     * 假期名称
     * @type {string}
     * @memberof BDCalHoliday
     */
    holidayName?: string | null;
    /**
     * 假期描述
     * @type {string}
     * @memberof BDCalHoliday
     */
    holidayDesc?: string | null;
    /**
     * 假期开始时间
     * @type {Date}
     * @memberof BDCalHoliday
     */
    startTime?: Date;
    /**
     * 假期结束时间
     * @type {Date}
     * @memberof BDCalHoliday
     */
    stopTime?: Date;
    /**
     * 添加时间
     * @type {Date}
     * @memberof BDCalHoliday
     */
    addedTime?: Date | null;
    /**
     * 假期停运设备编码
     * @type {string}
     * @memberof BDCalHoliday
     */
    resourceNo?: string | null;
    /**
     * 假期停运设备名称
     * @type {string}
     * @memberof BDCalHoliday
     */
    resourceName?: string | null;
    /**
     * 假期类型
     * @type {number}
     * @memberof BDCalHoliday
     */
    type?: number;
    /**
     * OrgId
     * @type {string}
     * @memberof BDCalHoliday
     */
    orgId?: string | null;
    /**
     * 日历信息表Id(弃用)
     * @type {string}
     * @memberof BDCalHoliday
     */
    calId?: string | null;
    /**
     * 休息总时长
     * @type {number}
     * @memberof BDCalHoliday
     */
    downTime?: number | null;
}
