/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 日历信息详情表
 * @export
 * @interface BDCalendarGeneral
 */
export interface BDCalendarGeneral {
    /**
     * 雪花Id
     * @type {number}
     * @memberof BDCalendarGeneral
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof BDCalendarGeneral
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof BDCalendarGeneral
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof BDCalendarGeneral
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof BDCalendarGeneral
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof BDCalendarGeneral
     */
    isDelete?: boolean;
    /**
     * Guid
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    guid?: string | null;
    /**
     * ResId(弃用)
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    resId?: string | null;
    /**
     * ResNo
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    resNo?: string | null;
    /**
     * OrgId
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    orgId?: string | null;
    /**
     * 日历编码
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    calNo?: string | null;
    /**
     * 日历名称
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    calName?: string | null;
    /**
     * 可用开始时间
     * @type {Date}
     * @memberof BDCalendarGeneral
     */
    beginDate?: Date | null;
    /**
     * 可用结束时间
     * @type {Date}
     * @memberof BDCalendarGeneral
     */
    endDate?: Date | null;
    /**
     * 备注
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    remark?: string | null;
    /**
     * 工作日
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    workDay?: string | null;
    /**
     * 班次1
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    shift1?: string | null;
    /**
     * 班次2
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    shift2?: string | null;
    /**
     * 班次3
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    shift3?: string | null;
    /**
     * 日历类型
     * @type {number}
     * @memberof BDCalendarGeneral
     */
    type?: number | null;
    /**
     * 优先级
     * @type {number}
     * @memberof BDCalendarGeneral
     */
    priority?: number | null;
    /**
     * 是否默认
     * @type {number}
     * @memberof BDCalendarGeneral
     */
    isDefault?: number | null;
    /**
     * 工作中心编码
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    workCenterNo?: string | null;
    /**
     * 管理日历信息表Id
     * @type {string}
     * @memberof BDCalendarGeneral
     */
    calId?: string | null;
}
