/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDChangeMatrixOutput
 */
export interface BDChangeMatrixOutput {
    /**
     * 
     * @type {number}
     * @memberof BDChangeMatrixOutput
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof BDChangeMatrixOutput
     */
    isChange?: number;
    /**
     * 
     * @type {number}
     * @memberof BDChangeMatrixOutput
     */
    clearPowder?: number;
    /**
     * 
     * @type {number}
     * @memberof BDChangeMatrixOutput
     */
    noClearPowder?: number;
    /**
     * 
     * @type {string}
     * @memberof BDChangeMatrixOutput
     */
    orgId?: string | null;
}
