/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 部门表
 * @export
 * @interface BDDepartment
 */
export interface BDDepartment {
    /**
     * 雪花Id
     * @type {number}
     * @memberof BDDepartment
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof BDDepartment
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof BDDepartment
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof BDDepartment
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof BDDepartment
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof BDDepartment
     */
    isDelete?: boolean;
    /**
     * 部门Id，唯一标识
     * @type {string}
     * @memberof BDDepartment
     */
    depId?: string | null;
    /**
     * 部门WorkshopId
     * @type {string}
     * @memberof BDDepartment
     */
    workshopId?: string | null;
    /**
     * 部门编号
     * @type {string}
     * @memberof BDDepartment
     */
    depNo: string;
    /**
     * 部门名称
     * @type {string}
     * @memberof BDDepartment
     */
    depName?: string | null;
    /**
     * 部门描述
     * @type {string}
     * @memberof BDDepartment
     */
    depDesc?: string | null;
    /**
     * 部门状态，默认为1
     * @type {number}
     * @memberof BDDepartment
     */
    status?: number | null;
    /**
     * 部门备注，现用于部门类型
     * @type {string}
     * @memberof BDDepartment
     */
    remarks: string;
    /**
     * 组织OrgId
     * @type {string}
     * @memberof BDDepartment
     */
    orgID?: string | null;
}
