/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDPartRoutingOutput
 */
export interface BDPartRoutingOutput {
    /**
     * 
     * @type {number}
     * @memberof BDPartRoutingOutput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BDPartRoutingOutput
     */
    partRoutingID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDPartRoutingOutput
     */
    partRoutingNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDPartRoutingOutput
     */
    partRoutingName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDPartRoutingOutput
     */
    orgId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDPartRoutingOutput
     */
    partId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDPartRoutingOutput
     */
    isStandard?: number;
}
