/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 产品信息表
 * @export
 * @interface BDPart
 */
export interface BDPart {
    /**
     * 雪花Id
     * @type {number}
     * @memberof BDPart
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof BDPart
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof BDPart
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof BDPart
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof BDPart
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof BDPart
     */
    isDelete?: boolean;
    /**
     * 产品Id
     * @type {string}
     * @memberof BDPart
     */
    partID?: string | null;
    /**
     * 组织Id
     * @type {string}
     * @memberof BDPart
     */
    orgID?: string | null;
    /**
     * 产品编号
     * @type {string}
     * @memberof BDPart
     */
    partNo?: string | null;
    /**
     * 产品名称
     * @type {string}
     * @memberof BDPart
     */
    partName?: string | null;
    /**
     * 产品描述
     * @type {string}
     * @memberof BDPart
     */
    partDesc?: string | null;
    /**
     * 产品类型
     * @type {number}
     * @memberof BDPart
     */
    partType?: number;
    /**
     * 产品类型2
     * @type {number}
     * @memberof BDPart
     */
    productType?: number;
    /**
     * 已弃用UnitId
     * @type {string}
     * @memberof BDPart
     */
    unitId?: string | null;
    /**
     * 已弃用AttachName
     * @type {string}
     * @memberof BDPart
     */
    attachName?: string | null;
    /**
     * 已弃用UrlPath
     * @type {string}
     * @memberof BDPart
     */
    urlPath?: string | null;
    /**
     * 已弃用产品图片链接
     * @type {string}
     * @memberof BDPart
     */
    attachment?: string | null;
    /**
     * 已弃用DefaultMBDecision
     * @type {number}
     * @memberof BDPart
     */
    defaultMBDecision?: number;
    /**
     * 产品分组
     * @type {string}
     * @memberof BDPart
     */
    mfgGroup?: string | null;
    /**
     * 已弃用LeadTime
     * @type {number}
     * @memberof BDPart
     */
    fullLeadTime?: number;
    /**
     * 计划编码
     * @type {string}
     * @memberof BDPart
     */
    plannerCode?: string | null;
    /**
     * 图纸编号
     * @type {string}
     * @memberof BDPart
     */
    drawingNo?: string | null;
    /**
     * 供货类型
     * @type {number}
     * @memberof BDPart
     */
    supplyType?: number;
    /**
     * 最小批量
     * @type {number}
     * @memberof BDPart
     */
    lotSize?: number;
    /**
     * 准备时间ST
     * @type {number}
     * @memberof BDPart
     */
    setupTimeST?: number;
    /**
     * 优先级
     * @type {number}
     * @memberof BDPart
     */
    resPriority?: number;
    /**
     * 产品分组编码
     * @type {string}
     * @memberof BDPart
     */
    groupNo?: string | null;
    /**
     * 产品所属分类
     * @type {string}
     * @memberof BDPart
     */
    familyNo?: string | null;
    /**
     * 类别
     * @type {string}
     * @memberof BDPart
     */
    categoryNo?: string | null;
}
