/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDResourceInput
 */
export interface BDResourceInput {
    /**
     * 当前页码
     * @type {number}
     * @memberof BDResourceInput
     */
    page?: number;
    /**
     * 页码容量
     * @type {number}
     * @memberof BDResourceInput
     */
    pageSize?: number;
    /**
     * 排序字段
     * @type {string}
     * @memberof BDResourceInput
     */
    field?: string | null;
    /**
     * 排序方向
     * @type {string}
     * @memberof BDResourceInput
     */
    order?: string | null;
    /**
     * 降序排序
     * @type {string}
     * @memberof BDResourceInput
     */
    descStr?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDResourceInput
     */
    resName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDResourceInput
     */
    resDesc?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDResourceInput
     */
    type?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceInput
     */
    resType?: number;
    /**
     * 
     * @type {string}
     * @memberof BDResourceInput
     */
    workCenterNo?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDResourceInput
     */
    units?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceInput
     */
    isAvailable?: number;
    /**
     * 
     * @type {string}
     * @memberof BDResourceInput
     */
    resNo?: string | null;
}
