/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDResourceOutput
 */
export interface BDResourceOutput {
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    resID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    depID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    resName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    resDesc?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    type?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    resType?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BDResourceOutput
     */
    isDefault?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    workCenterNo?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    units?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    programmable?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    isSeparable?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    isAvailable?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    isHeattreat?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    overtime?: number;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    orgID?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    processTime?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    setuptime1?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    setuptime2?: number;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    setuptime3?: number;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    versionSign?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDResourceOutput
     */
    isOld?: number;
    /**
     * 
     * @type {string}
     * @memberof BDResourceOutput
     */
    resNo?: string | null;
}
