/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 库存信息表
 * @export
 * @interface BDStock
 */
export interface BDStock {
    /**
     * 雪花Id
     * @type {number}
     * @memberof BDStock
     */
    id?: number;
    /**
     * 创建时间
     * @type {Date}
     * @memberof BDStock
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof BDStock
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof BDStock
     */
    createUserId?: number | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof BDStock
     */
    updateUserId?: number | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof BDStock
     */
    isDelete?: boolean;
    /**
     * 库存唯一标识
     * @type {string}
     * @memberof BDStock
     */
    stockId?: string | null;
    /**
     * 产品Id，管理产品表
     * @type {string}
     * @memberof BDStock
     */
    partID?: string | null;
    /**
     * 产品编码
     * @type {string}
     * @memberof BDStock
     */
    partNo?: string | null;
    /**
     * 产品描述
     * @type {string}
     * @memberof BDStock
     */
    partDesc?: string | null;
    /**
     * 组织ID
     * @type {string}
     * @memberof BDStock
     */
    orgID?: string | null;
    /**
     * Batch
     * @type {string}
     * @memberof BDStock
     */
    batch?: string | null;
    /**
     * 最大库存
     * @type {number}
     * @memberof BDStock
     */
    maxStock?: number;
    /**
     * 最小库存
     * @type {number}
     * @memberof BDStock
     */
    minStock?: number;
    /**
     * 已弃用ProdMode
     * @type {string}
     * @memberof BDStock
     */
    prodMode?: string | null;
    /**
     * 可用库存
     * @type {number}
     * @memberof BDStock
     */
    availableStock?: number;
    /**
     * 当前库存
     * @type {number}
     * @memberof BDStock
     */
    currentStock?: number;
    /**
     * 已弃用ErrorRate
     * @type {number}
     * @memberof BDStock
     */
    errorRate?: number;
    /**
     * 已弃用ErrorRate
     * @type {number}
     * @memberof BDStock
     */
    sourceType?: number;
    /**
     * 已弃用ErrorRate
     * @type {number}
     * @memberof BDStock
     */
    promiseDate?: number;
    /**
     * 已弃用SubInventoryCode
     * @type {string}
     * @memberof BDStock
     */
    subInventoryCode?: string | null;
    /**
     * 定位
     * @type {string}
     * @memberof BDStock
     */
    locator?: string | null;
    /**
     * 位置
     * @type {string}
     * @memberof BDStock
     */
    location?: string | null;
    /**
     * 转租(第三方)
     * @type {string}
     * @memberof BDStock
     */
    subLocation?: string | null;
    /**
     * 容器Bin
     * @type {string}
     * @memberof BDStock
     */
    bin?: string | null;
    /**
     * 批量
     * @type {string}
     * @memberof BDStock
     */
    lot?: string | null;
    /**
     * 已弃用Serial
     * @type {string}
     * @memberof BDStock
     */
    serial?: string | null;
    /**
     * 已弃用Serial
     * @type {number}
     * @memberof BDStock
     */
    atpQty?: number;
    /**
     * 承诺数量
     * @type {number}
     * @memberof BDStock
     */
    committedQty?: number;
    /**
     * 是否报废
     * @type {boolean}
     * @memberof BDStock
     */
    isBad?: boolean;
    /**
     * 可分配数量
     * @type {number}
     * @memberof BDStock
     */
    allocatedQTY?: number;
    /**
     * 可使用量
     * @type {number}
     * @memberof BDStock
     */
    availableQOH?: number;
    /**
     * 安全数量
     * @type {number}
     * @memberof BDStock
     */
    safetyStock?: number;
    /**
     * LeadTime
     * @type {number}
     * @memberof BDStock
     */
    leadTime?: number;
    /**
     * 缺少量
     * @type {number}
     * @memberof BDStock
     */
    shortageQty?: number;
    /**
     * 库存量
     * @type {number}
     * @memberof BDStock
     */
    inventoryCalculation?: number;
    /**
     * 是否是原材料
     * @type {number}
     * @memberof BDStock
     */
    isRawMaterial?: number;
    /**
     * 最小批量
     * @type {number}
     * @memberof BDStock
     */
    lotSize?: number;
    /**
     * 废品量
     * @type {number}
     * @memberof BDStock
     */
    scrap?: number;
    /**
     * 去毛刺
     * @type {number}
     * @memberof BDStock
     */
    deburring?: number;
    /**
     * 最小工序
     * @type {string}
     * @memberof BDStock
     */
    minOp?: string | null;
    /**
     * 粉料特性
     * @type {string}
     * @memberof BDStock
     */
    powderType?: string | null;
    /**
     * GP最小批量
     * @type {number}
     * @memberof BDStock
     */
    gpLotSize?: number;
}
