/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDStockInput
 */
export interface BDStockInput {
    /**
     * 当前页码
     * @type {number}
     * @memberof BDStockInput
     */
    page?: number;
    /**
     * 页码容量
     * @type {number}
     * @memberof BDStockInput
     */
    pageSize?: number;
    /**
     * 排序字段
     * @type {string}
     * @memberof BDStockInput
     */
    field?: string | null;
    /**
     * 排序方向
     * @type {string}
     * @memberof BDStockInput
     */
    order?: string | null;
    /**
     * 降序排序
     * @type {string}
     * @memberof BDStockInput
     */
    descStr?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockInput
     */
    partNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockInput
     */
    batch?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDStockInput
     */
    availableStock?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockInput
     */
    currentStock?: number;
    /**
     * 
     * @type {string}
     * @memberof BDStockInput
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockInput
     */
    bin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockInput
     */
    serial?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDStockInput
     */
    atpQty?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockInput
     */
    availableQOH?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockInput
     */
    isRawMaterial?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockInput
     */
    lotSize?: number;
}
