/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BDStockOutput
 */
export interface BDStockOutput {
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    stockId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    partID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    partNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    partDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    orgID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    batch?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    maxStock?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    minStock?: number;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    prodMode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    availableStock?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    currentStock?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    errorRate?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    sourceType?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    promiseDate?: number;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    subInventoryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    locator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    subLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    bin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    lot?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    serial?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    atpQty?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    committedQty?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BDStockOutput
     */
    isBad?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    allocatedQTY?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    availableQOH?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    safetyStock?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    leadTime?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    shortageQty?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    inventoryCalculation?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    isRawMaterial?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    lotSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    scrap?: number;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    deburring?: number;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    minOp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BDStockOutput
     */
    powderType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BDStockOutput
     */
    gpLotSize?: number;
}
