/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DeleteBDCalendarGeneralInput
 */
export interface DeleteBDCalendarGeneralInput {
    /**
     * 主键Id
     * @type {number}
     * @memberof DeleteBDCalendarGeneralInput
     */
    id: number;
}
