/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateBDCalendarGeneralInput
 */
export interface UpdateBDCalendarGeneralInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    guid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    resId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    resNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    orgId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    calNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    calName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBDCalendarGeneralInput
     */
    beginDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBDCalendarGeneralInput
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    remark?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    workDay?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    shift1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    shift2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    shift3?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalendarGeneralInput
     */
    type?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalendarGeneralInput
     */
    priority?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalendarGeneralInput
     */
    isDefault?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    workCenterNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalendarGeneralInput
     */
    calId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalendarGeneralInput
     */
    id: number;
}
