/* tslint:disable */
/* eslint-disable */
/**
 * 业务应用
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateBDCalHolidayInput
 */
export interface UpdateBDCalHolidayInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    holidayId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    holidayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    holidayDesc?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBDCalHolidayInput
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBDCalHolidayInput
     */
    stopTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBDCalHolidayInput
     */
    addedTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    resourceNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    resourceName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalHolidayInput
     */
    type?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    orgId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBDCalHolidayInput
     */
    calId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalHolidayInput
     */
    downTime?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateBDCalHolidayInput
     */
    id: number;
}
